##############################################################
# PTracer -- Pin (probe mode) attach/detach vehicle: ptattach.so.
# Built out of the kit:  make PIN_ROOT=<artifact root>/third_party/pin-3.20
##############################################################
ifdef PIN_ROOT
CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
else
CONFIG_ROOT := ../Config
endif
include $(CONFIG_ROOT)/makefile.config
include makefile.rules
include $(TOOLS_ROOT)/Config/makefile.default.rules
