#!/usr/bin/env bash
# Spindle-plus on pyperformance: CPython 3.12.13 built twice with clang-18 -O2 from one source tree.
#
#   third_party/spindle-plus/cpython/bin/python3.12    plain clang -O2 interpreter (the denominator, spindle_vanilla)
#   third_party/spindle-plus/cpython/bin/python3.12s   the same interpreter with its core compiled through the pass
#
# Two phases in one tree: first a plain `make python' (so the frozen modules and deep-freeze sources are generated by
# an uninstrumented interpreter), then the interpreter core -- Objects/, Python/, Parser/, Modules/main.c and
# Programs/python.c (main(), where the pass inserts the runtime's __init_main/__fini_main) -- is recompiled with
# `-fpass-plugin=libSTracerPlusPass.so' (STRACER_AUTO=1 runs the pass at the end of every TU's -O2 pipeline) and
# linked with the thread-safe runtime.  Extension modules and the shared libraries (libc, libm, ...) stay
# uninstrumented: Spindle-plus is a compile-time tracer and does not trace them.
# Both interpreters use the stdlib and extension modules of suites/pyperformance/cpython-cg (same CPython release and
# configuration: the ABI is the same), through a lib/ symlink, so the two arms differ only in the interpreter binary.
#
# The source is Python-3.12.13.tgz from python.org (sha256-checked; put the file into third_party/spindle-plus/ to
# build offline).  Exits non-zero on failure; build_baselines.sh then lists spindle_py as absent.
set -eu
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
S="$ROOT/third_party/spindle-plus"
D="$S/cpython"
VER=3.12.13
SHA=0816c4761c97ecdb3f50a3924de0a93fd78cb63ee8e6c04201ddfaedca500b0b
PASS="$S/pass/libSTracerPlusPass.so"
[ -x "$D/bin/python3.12" ] && [ -x "$D/bin/python3.12s" ] && { echo "spindle cpython: already built ($D/bin)"; exit 0; }
[ -f "$PASS" ] || { echo "spindle cpython: $PASS missing"; exit 1; }
cd "$S"
if [ ! -f "Python-$VER.tgz" ]; then
    python3 -c 'import sys, urllib.request; urllib.request.urlretrieve(sys.argv[1], sys.argv[2])' \
        "https://www.python.org/ftp/python/$VER/Python-$VER.tgz" "Python-$VER.tgz.part"
    mv "Python-$VER.tgz.part" "Python-$VER.tgz"
fi
echo "$SHA  Python-$VER.tgz" | sha256sum -c --quiet
mkdir -p cpython/bin
cd cpython
rm -rf "Python-$VER"
tar xzf "../Python-$VER.tgz"
cd "Python-$VER"
CC=clang-18 ./configure CFLAGS=-O2 > ../configure.log 2>&1
make -j"$(nproc)" python > ../make_vanilla.log 2>&1
cp python ../bin/python3.12
clang-18 -O2 -c "$S/stracer_lib_mt.c" -o ../stracer_rt.o
find Objects Python Parser -name '*.o' -delete
rm -f Modules/main.o Programs/python.o libpython3.12.a python
STRACER_AUTO=1 make -j"$(nproc)" python CFLAGS_NODIST="-fpass-plugin=$PASS" LIBS="-ldl $D/stracer_rt.o" \
    > ../make_spindle.log 2>&1
cp python ../bin/python3.12s
nm ../bin/python3.12s | grep -q ' T __init_main$'
cd ..
rm -rf "Python-$VER"
ln -sfn ../../../suites/pyperformance/cpython-cg/lib lib
echo "spindle cpython: built $D/bin/python3.12 and $D/bin/python3.12s"
